apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 99-set-core-passwd-master.yaml
  - 99-set-core-passwd-worker.yaml

patches:
- path: core-password-patch.yaml
  target:
    group: machineconfiguration.openshift.io
    version: v1
    kind: MachineConfig
    name: 99-set-core-user-password-master
- path: core-password-patch.yaml
  target:
    group: machineconfiguration.openshift.io
    version: v1
    kind: MachineConfig
    name: 99-set-core-user-password-worker
